version: '3'
services:
  goapp:
    container_name: "goapp"
    build: ./app
    volumes:
      - sync-volume:/go/src/github.com/mamoroom/mock-go-clean-arch/src/
    ports:
      - "80:80"
    command: "fresh"
volumes:
  sync-volume:
    external: true
